### ISSUE TITLE
where is exe ? 

### ISSUE THREAD

**Issue by HaxorGaruda** [DamonMohammadbagher/NativePayload_IP6DNS#1]
nice program...  but where is exe file ?

**Comment by DamonMohammadbagher** [comment]
sorry , you should compile this code yourself ;D by vs.net 2008 or 2015

**Comment by HaxorGaruda** [comment]
i has compile on linux with mono compiler .. but got this error : 
command : 
$ mcs -out:nativeIP6DNS.exe NativePayload_IP6DNS.cs 

got error :     
NativePayload_IP6DNS.cs(7,14): error CS0234: The type or namespace name `Data' does not exist in the namespace `System'. Are you missing `System.Data' assembly reference?
NativePayload_IP6DNS.cs(49,23): error CS0246: The type or namespace name `DataTable' could not be found. Are you missing an assembly reference?
NativePayload_IP6DNS.cs(171,29): error CS0246: The type or namespace name `DataTable' could not be found. Are you missing an assembly reference?
Compilation failed: 3 error(s), 0 warnings

**Comment by DamonMohammadbagher** [comment]
i don't have any idea about MONO and linux , please compile this in windows system , this error was related to system.data.dll or mscorlib.dll i think ,  i am not sure about this one ;)

**Comment by HaxorGaruda** [comment]
thanks bro.... you can close this .... :+1:
